# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./

RUN apk update 
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./deploy.conf /etc/nginx/nginx.conf

ARG VUE_APP_FIREBASE_API_KEY
ARG VUE_APP_FIREBASE_AUTH_DOMAIN
ARG VUE_APP_FIREBASE_PROJECT_ID
ARG VUE_APP_FIREBASE_STORAGE_BUCKET
ARG VUE_APP_FIREBASE_MESSAGING_SENDER_ID
ARG VUE_APP_FIREBASE_APP_ID
ARG VUE_APP_GOOGLE_MAPS_API_KEY
ARG VUE_APP_API_BASE_URL

ENV VUE_APP_FIREBASE_API_KEY=${VUE_APP_FIREBASE_API_KEY}
ENV VUE_APP_FIREBASE_AUTH_DOMAIN=${VUE_APP_FIREBASE_AUTH_DOMAIN}
ENV VUE_APP_FIREBASE_PROJECT_ID=${VUE_APP_FIREBASE_PROJECT_ID}
ENV VUE_APP_FIREBASE_STORAGE_BUCKET=${VUE_APP_FIREBASE_STORAGE_BUCKET}
ENV VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${VUE_APP_FIREBASE_MESSAGING_SENDER_ID}
ENV VUE_APP_FIREBASE_APP_ID=${VUE_APP_FIREBASE_APP_ID}
ENV VUE_APP_GOOGLE_MAPS_API_KEY=${VUE_APP_GOOGLE_MAPS_API_KEY}
ENV VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]